---

- name: Create Policy Access Rule
  zscaler.zpacloud.zpa_policy_access_rule:
    provider: "{{ zscaler_zpa }}"
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    action: '{{ item.action }}'
    rule_order: '{{ item.rule_order }}'
    app_connector_group_ids: '{{ item.app_connector_group_ids | default([]) }}'
    app_server_group_ids: '{{ item.app_server_group_ids | default([]) }}'
    operator: '{{ item.operator | default("AND") }}'
    conditions:
      - operator: '{{ item.operator | default("AND") }}'
        operands:
          - idp_id: '{{ item.idp_id | default([]) }}'
            object_type: '{{ item.object_type | default("SCIM_GROUP") }}'
    state: '{{ item.state | default("present") }}'
  loop: '{{ zpa_policy_access_rules }}'
