---

- name: Create Firewall Rules
  zscaler.ziacloud.zia_cloud_firewall_rule:
    provider: '{{ zscaler_zia }}'
    name: '{{ item.name }}'
    order: '{{ item.order }}'
    description: '{{ item.description }}'
    enabled: '{{ item.enabled }}'
    groups: '{{ item.groups | default(omit) }}'
    departments: '{{ item.departments | default(omit) }}'
    locations: '{{ item.locations | default(omit) }}'
    location_groups: '{{ item.location_groups | default(omit) }}'
    devices: '{{ item.devices | default(omit) }}'
    device_groups: '{{ item.device_groups | default(omit) }}'
    device_trust_levels: '{{ item.device_trust_levels | default(omit) }}'
    labels: '{{ item.labels | default(omit) }}'
    nw_service_groups: '{{ item.nw_service_groups | default(omit) }}'
    nw_services: '{{ item.nw_services | default(omit) }}'
    nw_application_groups: '{{ item.nw_application_groups | default(omit) }}'
    nw_applications: '{{ item.nw_applications | default(omit) }}'  # Locate application ID here: '{{ role_path }}/files/nw_applications.txt'
    app_service_groups: '{{ item.app_service_groups | default(omit) }}'
    src_ip_groups: '{{ item.src_ip_groups | default(omit) }}'
    src_ips: '{{ item.src_ips | default(omit) }}'
    exclude_src_countries: '{{ item.exclude_src_countries | default(false) }}'
    source_countries: '{{ item.source_countries | default(omit) }}'
    dest_ip_groups: '{{ item.dest_ip_groups | default(omit) }}'
    dest_addresses: '{{ item.dest_addresses | default(omit) }}'
    dest_countries: '{{ item.dest_countries | default(omit) }}'
    dest_ip_categories: '{{ item.dest_ip_categories | default(omit) }}'
    action: '{{ item.action }}'
    enable_full_logging: '{{ item.enable_full_logging | default(false) }}'
    state: '{{ item.state }}'
  loop: '{{ zia_cloud_firewall_rule }}'
