---

- name: Gather Information Details for all Groups
  zscaler.ziacloud.zia_user_management_groups_info:
    provider: '{{ zscaler_zia }}'
  register: id_groups

- name: Register each Group ID as a separate variable
  ansible.builtin.set_fact:
    group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}: "{{ item.id }}"
  loop: "{{ id_groups.groups }}"
  loop_control:
    label: "Group name: group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}"

- name: Delete file with all Groups
  ansible.builtin.file:
    path: '{{ role_path }}/files/groups.txt'
    state: absent

- name: Register all Groups to a file
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/files/groups.txt'
    create: true
    mode: '0644'
    state: present
    line: |
      Group name: group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}
      ID: {{ item.id }}
  loop: "{{ id_groups.groups }}"
