---

- name: Gather Information Details for all Groups
  zscaler.ziacloud.zia_user_management_groups_info:
    provider: '{{ zscaler_zia }}'
  register: id_groups

- name: Register each app connector group ID as a separate variable
  set_fact:
    group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}: "{{ item.id }}"
  loop: "{{ id_groups.groups }}"
  loop_control:
    label: "Group name: group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}"
