---

- name: Configure Advanced Threat Protection Settings
  zscaler.ziacloud.zia_atp_settings:
    provider: '{{ zscaler_zia }}'
    risk_tolerance: '{{ zia_atp_settings.risk_tolerance | default("30") }}'
    risk_tolerance_capture: '{{ zia_atp_settings.risk_tolerance_capture | default("false") }}'
    cmd_ctl_server_blocked: '{{ zia_atp_settings.cmd_ctl_server_blocked | default("true") }}'
    cmd_ctl_server_capture: '{{ zia_atp_settings.cmd_ctl_server_capture | default("false") }}'
    cmd_ctl_traffic_blocked: '{{ zia_atp_settings.cmd_ctl_traffic_blocked | default("true") }}'
    cmd_ctl_traffic_capture: '{{ zia_atp_settings.cmd_ctl_traffic_capture | default("false") }}'
    malware_sites_blocked: '{{ zia_atp_settings.malware_sites_blocked | default("true") }}'
    malware_sites_capture: '{{ zia_atp_settings.malware_sites_capture | default("false") }}'
    active_x_blocked: '{{ zia_atp_settings.active_x_blocked | default("true") }}'
    active_x_capture: '{{ zia_atp_settings.active_x_capture | default("false") }}'
    browser_exploits_blocked: '{{ zia_atp_settings.browser_exploits_blocked | default("true") }}'
    browser_exploits_capture: '{{ zia_atp_settings.browser_exploits_capture | default("false") }}'
    file_format_vunerabilites_blocked: '{{ zia_atp_settings.file_format_vunerabilites_blocked | default("true") }}'
    file_format_vunerabilites_capture: '{{ zia_atp_settings.file_format_vunerabilites_capture | default("false") }}'
    known_phishing_sites_blocked: '{{ zia_atp_settings.known_phishing_sites_blocked | default("true") }}'
    known_phishing_sites_capture: '{{ zia_atp_settings.known_phishing_sites_capture | default("false") }}'
    suspected_phishing_sites_blocked: '{{ zia_atp_settings.suspected_phishing_sites_blocked | default("true") }}'
    suspected_phishing_sites_capture: '{{ zia_atp_settings.suspected_phishing_sites_capture | default("false") }}'
    suspect_adware_spyware_sites_blocked: '{{ zia_atp_settings.suspect_adware_spyware_sites_blocked | default("true") }}'
    suspect_adware_spyware_sites_capture: '{{ zia_atp_settings.suspect_adware_spyware_sites_capture | default("false") }}'
    webspam_blocked: '{{ zia_atp_settings.webspam_blocked | default("true") }}'
    webspam_capture: '{{ zia_atp_settings.webspam_capture | default("false") }}'
    irc_tunnelling_blocked: '{{ zia_atp_settings.irc_tunnelling_blocked | default("true") }}'
    irc_tunnelling_capture: '{{ zia_atp_settings.irc_tunnelling_capture | default("false") }}'
    anonymizer_blocked: '{{ zia_atp_settings.anonymizer_blocked | default("true") }}'
    anonymizer_capture: '{{ zia_atp_settings.anonymizer_capture | default("false") }}'
    cookie_stealing_blocked: '{{ zia_atp_settings.cookie_stealing_blocked | default("true") }}'
    cookie_stealing_pcap_enabled: '{{ zia_atp_settings.cookie_stealing_pcap_enabled | default("false") }}'
    potential_malicious_requests_blocked: '{{ zia_atp_settings.potential_malicious_requests_blocked | default("true") }}'
    potential_malicious_requests_capture: '{{ zia_atp_settings.potential_malicious_requests_capture | default("false") }}'
    blocked_countries: '{{ zia_atp_settings.blocked_countries | default([]) }}'
    block_countries_capture: '{{ zia_atp_settings.block_countries_capture | default("false") }}'
    bit_torrent_blocked: '{{ zia_atp_settings.bit_torrent_blocked | default("true") }}'
    bit_torrent_capture: '{{ zia_atp_settings.bit_torrent_capture | default("false") }}'
    tor_blocked: '{{ zia_atp_settings.tor_blocked | default("true") }}'
    tor_capture: '{{ zia_atp_settings.tor_capture | default("false") }}'
    google_talk_blocked: '{{ zia_atp_settings.google_talk_blocked | default("false") }}'
    google_talk_capture: '{{ zia_atp_settings.google_talk_capture | default("false") }}'
    ssh_tunnelling_blocked: '{{ zia_atp_settings.ssh_tunnelling_blocked | default("true") }}'
    ssh_tunnelling_capture: '{{ zia_atp_settings.ssh_tunnelling_capture | default("false") }}'
    crypto_mining_blocked: '{{ zia_atp_settings.crypto_mining_blocked | default("true") }}'
    crypto_mining_capture: '{{ zia_atp_settings.crypto_mining_capture | default("false") }}'
    ad_spyware_sites_blocked: '{{ zia_atp_settings.ad_spyware_sites_blocked | default("true") }}'
    ad_spyware_sites_capture: '{{ zia_atp_settings.ad_spyware_sites_capture | default("false") }}'
    dga_domains_blocked: '{{ zia_atp_settings.dga_domains_blocked | default("true") }}'
    dga_domains_capture: '{{ zia_atp_settings.dga_domains_capture | default("false") }}'
    alert_for_unknown_or_suspicious_c2_traffic: '{{ zia_atp_settings.alert_for_unknown_or_suspicious_c2_traffic | default("true") }}'
    malicious_urls_capture: '{{ zia_atp_settings.malicious_urls_capture | default("false") }}'
