---

- name: Create Cloud App Control Policy Rules
  zscaler.ziacloud.zia_cloud_app_control_rules:
    provider: '{{ zscaler_zia }}'
    state: '{{ item.state }}'
    name: '{{ item.name }}'
    order: '{{ item.order }}'
    description: '{{ item.description }}'
    enabled: '{{ item.enabled }}'
    rule_type: '{{ item.rule_type | default(omit) }}'
    groups: '{{ item.groups | default(omit) }}'
    departments: '{{ item.departments | default(omit) }}'
    locations: '{{ item.locations | default(omit) }}'
    location_groups: '{{ item.location_groups | default(omit) }}'
    devices: '{{ item.devices | default(omit) }}'
    device_groups: '{{ item.device_groups | default(omit) }}'
    device_trust_levels: '{{ item.device_trust_levels | default(omit) }}'
    labels: '{{ item.labels | default(omit) }}'
    request_methods: '{{ item.request_methods | default(omit) }}'
    protocols: '{{ item.protocols | default(omit) }}'
    user_agent_types: '{{ item.user_agent_types | default(omit) }}'
    actions: '{{ item.actions }}'
    applications: '{{ item.applications }}'
    cloud_app_instances: '{{ item.cloud_app_instances | default(omit)}}'
    tenancy_profile_ids: '{{ item.tenancy_profile_ids | default(omit) }}'
  loop: '{{ zia_cloud_app_control_rules }}'
