---

version: 3

env:

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  zia_activate_changes:
    cmds:
      - ansible-playbook playbooks/zia/zia_activate_changes.yaml
    desc: Activate pending changes in Zscaler Internet Access (ZIA)

  zia_ssl_inspection_rules:
    cmds:
      - ansible-playbook playbooks/zia/zia_ssl_inspection_rules.yaml
    desc: Create or update SSL inspection rules in Zscaler Internet Access (ZIA)

  zia_url_categories:
    cmds:
      - ansible-playbook playbooks/zia/zia_url_categories.yaml
    desc: Create or update custom URL categories in Zscaler Internet Access (ZIA)

  zpa_ba_certificate:
    cmds:
      - ansible-playbook playbooks/zpa/zpa_ba_certificate.yaml
    desc: Create or update the Zscaler Private Access (ZPA) Browser Access certificates