---

- name: Gather Information Details for all Source IP Groups
  zscaler.ziacloud.zia_cloud_firewall_ip_source_groups_info:
    provider: '{{ zscaler_zia }}'
  register: id_src_ip_groups

- name: Register each Source IP Group ID as a separate variable
  ansible.builtin.set_fact:
    src_ip_group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}: "{{ item.id }}"
  loop: "{{ id_src_ip_groups.groups }}"
  loop_control:
    label: "Source IP Group: src_ip_group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}"

- name: Delete file with all Source IP Groups
  ansible.builtin.file:
    path: '{{ role_path }}/files/src_ip_groups.txt'
    state: absent

- name: Register all Source IP Groups to a file
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/files/src_ip_groups.txt'
    create: true
    mode: '0644'
    state: present
    line: |
      Source IP Group: src_ip_group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}"
      ID: {{ item.id }}
  loop: "{{ id_src_ip_groups.groups }}"
