---

zia_ssl_inspection_rules:
  - name: 'DoNotInspect / Finance'
    order: 1
    description: 'Do not inspect finance categories - e.g., banking, financial services, etc.'
    enabled: true
    labels: 4532654
    groups: []
    departments: []
    locations: []
    location_groups: []
    url_categories:
      - FINANCE
    cloud_applications: []
    action:
      type: DO_NOT_DECRYPT
      do_not_decrypt_sub_actions:
        # block_ssl_traffic_with_no_sni_enabled: true
        # bypass_other_policies: false
        min_tls_version: SERVER_TLS_1_2
        # ocsp_check: true
        # server_certificates: BLOCK
    state: present
  - name: 'Inspect / Microsoft Apps'
    order: 2
    description: 'Inspect Microsoft Apps - to enable tenant restrictions'
    enabled: true
    labels: 4532654
    groups: []
    departments: []
    locations: []
    location_groups: []
    # url_categories:  # empty array is not allowed - comment out if you do not want to use url_categories
    cloud_applications:
      - MSLOGINSERVICES
      - SHAREPOINTONLINE
    action:
      type: DECRYPT
      # override_default_certificate: false
      # show_eun: true
      # show_eunatp: true
      # decrypt_sub_actions:  # No need for this since the default values are already set - use defaults as a reference
      #   block_ssl_traffic_with_no_sni_enabled: true
      #   block_undecrypt: true
      #   http2_enabled: true
      #   min_client_tls_version: CLIENT_TLS_1_3
      #   min_server_tls_version: SERVER_TLS_1_3
      #   ocsp_check: true
      #   server_certificates: BLOCK
    state: present
