# There are several ways to securely store sensitive data used by Ansible.
# This example uses [Pass](https://www.passwordstore.org) to store credentials used to authenticate with Zscaler ZIA and ZPA.
# Note that the ZPA collection currently does not support OneAPI and relies on the old Legacy API.
zscaler_zia:
  client_id: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zia/client_id") }}'
  client_secret: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zia/client_secret") }}'
  vanity_domain: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zia/vanity_domain") }}'
  # cloud: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zia/cloud") | default(omit) }}'  # The cloud key is optional and only required when authenticating to other environments i.e beta

zscaler_zpa:
  client_id: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zpa/client_id") }}'
  client_secret:   '{{ lookup("community.general.passwordstore", "ansible/zscaler/zpa/client_secret") }}'
  customer_id: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zpa/customer_id") }}'
  cloud: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zpa/cloud") | default(omit) }}'

# Another way to securely store sensitive data is to use environment variables.
# This example uses environment variables to store credentials used to authenticate with Zscaler OneAPI.
# To use this method, you will need to rename the key 'zscaler_zia_env' to 'zscaler_zia'.
zscaler_zia_env:
  client_id: "{{ lookup('ansible.builtin.env', 'ZSCALER_CLIENT_ID') }}"
  client_secret: "{{ lookup('ansible.builtin.env', 'ZSCALER_CLIENT_SECRET') }}"
  vanity_domain: "{{ lookup('ansible.builtin.env', 'ZSCALER_VANITY_DOMAIN') }}"
  # cloud: "{{ lookup('ansible.builtin.env', 'ZSCALER_CLOUD') | default(omit) }}"
