---

- name: Gather Information Details for all Destination IP Groups
  zscaler.ziacloud.zia_cloud_firewall_ip_destination_groups_info:
    provider: '{{ zscaler_zia }}'
  register: id_dest_ip_groups

- name: Register each Destination IP Group ID as a separate variable
  ansible.builtin.set_fact:
    dest_ip_group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}: "{{ item.id }}"
  loop: "{{ id_dest_ip_groups.groups }}"
  loop_control:
    label: "Destination IP Group: dest_ip_group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}"
