---

- name: Get Segment Group Info for all groups
  zscaler.zpacloud.zpa_segment_group_info:
    provider: "{{ zscaler_zpa }}"
  register: segment_group

- name: Register each Segment Group ID as a separate variable
  ansible.builtin.set_fact:
    segment_group_id_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}: "{{ item.id }}"
  loop: "{{ segment_group.groups }}"

- name: Display all registered variables
  ansible.builtin.debug:
    msg: |
      Segment Group Name: {{ item.name }}
      New Segment Group Name: segment_group_id_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}
      Segment Group ID: {{ item.id }}
  loop: "{{ segment_group.groups }}"
  loop_control:
    label: "{{ item.name }}"

- name: Register all Segment Group IDs to a file
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/files/segment_groups.txt'
    create: true
    mode: '0644'
    state: present
    line: |
      Segment Group Name: {{ item.name }}
      New Segment Group Name: segment_group_id_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}
      Segment Group ID: {{ item.id }}
  loop: "{{ segment_group.groups }}"
  loop_control:
    label: "{{ item.name }}"
