---

- name: Gather Information Details for all Network Services
  zscaler.ziacloud.zia_cloud_firewall_network_services_info:
    provider: '{{ zscaler_zia }}'
  register: id_nw_services

- name: Register each Network Service ID as a separate variable
  ansible.builtin.set_fact:
    nw_service_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}: "{{ item.id }}"
  loop: "{{ id_nw_services.services }}"
  loop_control:
    label: "Network Service: nw_service_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}"

- name: Delete file with all Network Services
  ansible.builtin.file:
    path: '{{ role_path }}/files/nw_services.txt'
    state: absent

- name: Register all Network Services to a file
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/files/nw_services.txt'
    create: true
    mode: '0644'
    state: present
    line: |
      Network Service: nw_service_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}
      ID: {{ item.id }}
  loop: "{{ id_nw_services.services }}"
