---

- name: Gather Information Details for all Network Services Groups
  zscaler.ziacloud.zia_cloud_firewall_network_services_groups_info:
    provider: '{{ zscaler_zia }}'
  register: id_nw_service_groups

- name: Register each Network Service Group ID as a separate variable
  ansible.builtin.set_fact:
    nw_serivce_group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}: "{{ item.id }}"
  loop: "{{ id_nw_service_groups.groups }}"
  loop_control:
    label: "Network Service Group: nw_service_group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}"

- name: Delete file with all Network Services Groups
  ansible.builtin.file:
    path: '{{ role_path }}/files/nw_service_groups.txt'
    state: absent

- name: Register all Network Services Groups to a file
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/files/nw_service_groups.txt'
    create: true
    mode: '0644'
    state: present
    line: |
      Network Service Group: nw_service_group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}
      ID: {{ item.id }}
  loop: "{{ id_nw_service_groups.groups }}"
