---

- name: Gather Information Details for all Location Groups
  zscaler.ziacloud.zia_location_groups_info:
    provider: '{{ zscaler_zia }}'
  register: id_location_groups

- name: Register each Location Group ID as a separate variable
  ansible.builtin.set_fact:
    location_group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}: "{{ item.id }}"
  loop: "{{ id_location_groups.locations }}"
  loop_control:
    label: "Location Group name: location_group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}"

- name: Delete file with all Location Groups
  ansible.builtin.file:
    path: '{{ role_path }}/files/location_groups.txt'
    state: absent

- name: Register all Location Groups to a file
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/files/location_groups.txt'
    create: true
    mode: '0644'
    state: present
    line: |
      Location Group name: location_group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}
      ID: {{ item.id }}
  loop: "{{ id_location_groups.locations }}"
