---

- name: Get App Connector Group Info for all groups
  zscaler.zpacloud.zpa_app_connector_group_info:
    provider: "{{ zscaler_zpa }}"
  register: app_connector_group

- name: Register each App Connector Group ID as a separate variable
  ansible.builtin.set_fact:
    app_connector_group_id_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}: "{{ item.id }}"
  loop: "{{ app_connector_group.groups }}"

- name: Display all registered variables
  ansible.builtin.debug:
    msg: |
      App Connector Group Name: {{ item.name }}
      New App Connector Group Name: app_connector_group_id_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}
      App Connector Group ID: {{ item.id }}
  loop: "{{ app_connector_group.groups }}"
  loop_control:
    label: "{{ item.name }}"

- name: Register all App Connector Group IDs to a file
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/files/app_connector_groups.txt'
    create: true
    mode: '0644'
    state: present
    line: |
      App Connector Group Name: {{ item.name }}
      New App Connector Group Name: app_connector_group_id_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}
      App Connector Group ID: {{ item.id }}
  loop: "{{ app_connector_group.groups }}"
  loop_control:
    label: "{{ item.name }}"
