---

zia_url_filtering_rules:
  - name: 'Block Adult Material'
    order: 1
    description: 'Block adult material'
    enabled: true
    url_categories:
      - PORNOGRAPHY
    groups: []
    departments: []
    locations: []
    location_groups: []
    devices: []
    device_groups: []
    device_trust_levels: ANY
    labels: 4532654
    request_methods: [GET, POST, PUT, DELETE, HEAD, OPTIONS, TRACE, CONNECT, PATCH, PROPFIND, PROPPATCH, MOVE, MKCOL, LOCK, COPY, UNLOCK, OTHER]
    protocols:
      - HTTP_RULE
      - HTTPS_RULE
    user_agent_types: []
    action: BLOCK
    state: present
  - name: 'Block High Risk Categories'
    order: 2
    description: 'Block high risk categories'
    enabled: true
    url_categories:
      - ADWARE_OR_SPYWARE
      - ANONYMIZER
      - DYNAMIC_DNS
      - NEWLY_REG_DOMAINS
      - NEWLY_REVIVED_DOMAINS
      - OTHER_ILLEGAL_OR_QUESTIONABLE
      - OTHER_SECURITY
      - P2P_COMMUNICATION
    groups: []
    departments: []
    locations: []
    location_groups: []
    devices: []
    device_groups: []
    device_trust_levels: ANY
    labels: 4532654
    request_methods: [GET, POST, PUT, DELETE, HEAD, OPTIONS, TRACE, CONNECT, PATCH, PROPFIND, PROPPATCH, MOVE, MKCOL, LOCK, COPY, UNLOCK, OTHER]
    protocols:
      - HTTP_RULE
      - HTTPS_RULE
    user_agent_types:
      - CHROME
      - FIREFOX
      - MSCHREDGE
      - MSEDGE
      - MSIE
      - OPERA
      - SAFARI
    action: BLOCK
    state: present
  - name: 'Exemptet URL Categories'
    order: 3
    description: 'Exempted URL categories'
    enabled: true
    url_categories:
      - CUSTOM_18  # 'Custom URLs - Borgermeister'
    groups: []
    departments: []
    locations: []
    location_groups: []
    devices: []
    device_groups: []
    device_trust_levels: ANY
    labels: 4532654
    request_methods: [GET, POST, PUT, DELETE, HEAD, OPTIONS, TRACE, CONNECT, PATCH, PROPFIND, PROPPATCH, MOVE, MKCOL, LOCK, COPY, UNLOCK, OTHER]
    protocols:
      - HTTP_RULE
      - HTTPS_RULE
    user_agent_types:
      - CHROME
      - FIREFOX
      - MSCHREDGE
      - MSEDGE
      - MSIE
      - OPERA
      - SAFARI
    action: ALLOW
    state: present
  - name: 'Browser Isolation'
    order: 4
    description: |-
      Browser isolation for high risk categories.
      Apply Browser Isolation when Device Trust Level is 'Low', 'Medium' or 'Unknown'.
    enabled: true
    url_categories:
      - MISCELLANEOUS_OR_UNKNOWN
      - OTHER_MISCELLANEOUS
    groups: []
    departments: []
    locations: []
    location_groups: []
    devices: []
    device_groups: []
    device_trust_levels: [LOW_TRUST, MEDIUM_TRUST, UNKNOWN_DEVICETRUSTLEVEL]
    labels: 4532654
    request_methods: [GET, POST, PUT, DELETE, HEAD, OPTIONS, TRACE, CONNECT, PATCH, PROPFIND, PROPPATCH, MOVE, MKCOL, LOCK, COPY, UNLOCK, OTHER]
    protocols:
      - HTTP_RULE
      - HTTPS_RULE
    user_agent_types:
      - CHROME
      - FIREFOX
      - MSCHREDGE
      - MSEDGE
      - MSIE
      - OPERA
      - SAFARI
    action: ISOLATE
    block_override: false
    # override_users:
    # override_groups:
    cbi_profile:
      id: e7947be1-16a8-4b84-a346-20ade07be859
      name: 'Borgermeister Browser Isolation'
      url: 'https://redirect.isolation.zscaler.com/tenant/12176b75e351/profile/e7947be1-16a8-4b84-a346-20ade07be859'
    state: present
