---

- name: Gather Information Details for all URL Categories
  zscaler.ziacloud.zia_url_categories_info:
    provider: '{{ zscaler_zia }}'
  register: zia_url_categories_info

- name: Delete file with all URL Categories
  ansible.builtin.file:
    path: '{{ role_path }}/files/url_categories.txt'
    state: absent

- name: Register all URL Categories to a file
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/files/url_categories.txt'
    create: true
    mode: '0644'
    state: present
    line: |
      ID: {{ item.id }}
      Type: {{ item.type }}
      Configured Name: {{ item.configured_name | default('') }}
  loop: "{{ zia_url_categories_info.categories }}"
