---

# Zscaler Provider Connection Parameters
zscaler_zia:
  client_id: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zia/client_id") }}'
  client_secret: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zia/client_secret") }}'
  vanity_domain: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zia/vanity_domain") }}'
  # cloud: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zia/cloud") | default(omit) }}'  # The cloud key is optional and only required when authenticating to other environments i.e beta

# Default variables for zscaler_zia_custom_url_categories role
zia_custom_url_categories:
  - name: 'TLS Inspection Bypass - Example'
    description: 'This category is for bypassing TLS inspection.'
    custom_category: true
    type: 'URL_CATEGORY'
    super_category: 'USER_DEFINED'
    db_categorized_urls:
      - configuration.apple.com
      - courier.push.apple.com
      - init.push.apple.com
      - gsp-ssl-ls.apple.com
      - gdmf.apple.com
      - .cfn-apple.com
      - mesu.apple.com
    # urls: # Custom URLs that will override the 'URLs Retaining Parent Category'
    state: present
