---

- name: Create SSL Inspection Rules
  zscaler.ziacloud.zia_ssl_inspection_rules:
    provider: '{{ zscaler_zia }}'
    order: '{{ item.order }}'
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    enabled: '{{ item.enabled }}'
    labels: '{{ item.labels | default(omit) }}'
    source_ip_groups: '{{ item.source_ip_groups | default(omit) }}'
    groups: '{{ item.groups | default(omit) }}'
    departments: '{{ item.departments | default(omit) }}'
    locations: '{{ item.locations | default(omit) }}'
    location_groups: '{{ item.location_groups | default(omit) }}'
    url_categories: '{{ item.url_categories | default(omit) }}'
    cloud_applications: '{{ item.cloud_applications | default(omit) }}'
    action: '{{ item.action }}'
    road_warrior_for_kerberos: '{{ item.road_warrior_for_kerberos | default(false) }}'
    state: '{{ item.state }}'
  loop: '{{ zia_ssl_inspection_rules }}'
