---

- name: Gather Information Details for all Cloud Applications - App Policy
  zscaler.ziacloud.zia_cloud_applications_info:
    provider: '{{ zscaler_zia }}'
    mode: app_policy
  register: cloud_applications_app

- name: Delete file with all Cloud Applications - App Policy
  ansible.builtin.file:
    path: '{{ role_path }}/files/cloud_applications_app.txt'
    state: absent

- name: Register all Cloud Applications to a file - App Policy
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/files/cloud_applications_app.txt'
    create: true
    mode: '0644'
    state: present
    line: |
      Application: {{ item.app }}
      Parent Category: {{ item.parent_name | default('N/A') }}
  loop: "{{ cloud_applications_app.applications }}"

- name: Gather Information Details for all Cloud Applications - SSL Policy
  zscaler.ziacloud.zia_cloud_applications_info:
    provider: '{{ zscaler_zia }}'
    mode: ssl_policy
  register: cloud_applications_ssl

- name: Delete file with all Cloud Applications - SSL Policy
  ansible.builtin.file:
    path: '{{ role_path }}/files/cloud_applications_ssl.txt'
    state: absent

- name: Register all Cloud Applications to a file - SSL Policy
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/files/cloud_applications_ssl.txt'
    create: true
    mode: '0644'
    state: present
    line: |
      Application: {{ item.app }}
      Parent Category: {{ item.parent_name | default('N/A') }}
  loop: "{{ cloud_applications_ssl.applications }}"
