---

- name: Ansible Roles to configure Zscaler Internet Access
  hosts: localhost

  roles:
    # - role: zscaler_zia/zia_cloud_browser_isolation_profile_info
    # - role: zscaler_zia/zia_location_management_info
    # - role: zscaler_zia/zia_location_groups_info
    # - role: zscaler_zia/zia_user_management_groups_info
    # - role: zscaler_zia/zia_user_management_department_info
    # - role: zscaler_zia/zia_cloud_firewall_ip_source_groups_info
    # - role: zscaler_zia/zia_cloud_firewall_ip_destination_groups_info
    # - role: zscaler_zia/zia_cloud_firewall_network_services_info
    # - role: zscaler_zia/zia_cloud_firewall_network_services_groups_info
    # - role: zscaler_zia/zia_cloud_firewall_network_application_info
    # - role: zscaler_zia/zia_cloud_firewall_network_application_group_info
    # - role: zscaler_zia/zia_url_categories
    # - role: zscaler_zia/zia_ssl_inspection_rules_info
    - role: zscaler_zia/zia_ssl_inspection_rules
    # - role: zscaler_zia/zia_url_filtering_rule_info
    - role: zscaler_zia/zia_url_filtering_rules
    # - role: zscaler_zia/zia_cloud_firewall_rule_info
    - role: zscaler_zia/zia_cloud_firewall_rule
    - role: zscaler_zia/zia_activation_status

...
