---

- name: Gather Information Details for all Departments
  zscaler.ziacloud.zia_user_management_department_info:
    provider: '{{ zscaler_zia }}'
  register: id_departments

- name: Register each Department ID as a separate variable
  ansible.builtin.set_fact:
    department_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}: "{{ item.id }}"
  loop: "{{ id_departments.departments }}"
  loop_control:
    label: "Department name: department_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}"

- name: Delete file with all Departments
  ansible.builtin.file:
    path: '{{ role_path }}/files/departments.txt'
    state: absent

- name: Register all Departments to a file
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/files/departments.txt'
    create: true
    mode: '0644'
    state: present
    line: |
      Department name: department_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}
      ID: {{ item.id }}
  loop: "{{ id_departments.departments }}"
