---

- name: Gather Information Details for all Departments
  zscaler.ziacloud.zia_user_management_department_info:
    provider: '{{ zscaler_zia }}'
  register: id_departments

- name: Register each Department ID as a separate variable
  set_fact:
    department_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}: "{{ item.id }}"
  loop: "{{ id_departments.departments}}"
  loop_control:
    label: "Department name: department_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}"
