---

- name: Gather Information Details for all Network Application Groups
  zscaler.ziacloud.zia_cloud_firewall_network_application_group_info:
    provider: '{{ zscaler_zia }}'
  register: id_nw_application_groups

- name: Register each Network Application Group ID as a separate variable
  ansible.builtin.set_fact:
    nw_application_group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}: "{{ item.id }}"
  loop: "{{ id_nw_application_groups.groups }}"
  loop_control:
    label: "Network Application Group: nw_application_group_{{ item.name | replace(' ', '') | replace('-', '') | replace('_', '') | lower }}"
