---

# Zscaler Provider Connection Parameters
zscaler_zia:
  client_id: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zia/client_id") }}'
  client_secret: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zia/client_secret") }}'
  vanity_domain: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zia/vanity_domain") }}'
  # cloud: '{{ lookup("community.general.passwordstore", "ansible/zscaler/zia/cloud") | default(omit) }}'  # The cloud key is optional and only required when authenticating to other environments i.e beta

# Be aware that if you change the name of an existing rule in Ansible,
# a new rule will be created and Ansible will lose track of the old one.
# The old rule will not be deleted, so you will need to delete it manually.
# To prevent this behavior, you can have Ansible reference the rule by its ID.
# I personally think this is to cumbersome, so I just use the name of the rule.
zia_ssl_inspection_rules:
  - name: 'SSL Inspection Rule'
    order: 14
    description: 'Give a useful description'
    enabled: true
    groups:
      - '{{ group_borgermeister }}'
    departments:
      - '{{ department_borgermeisterit }}'
    locations:
      - '{{ location_borgermeisterhome }}'
    location_groups: []
    url_categories:
      - PROFESSIONAL_SERVICES
    cloud_applications:
      - MSLOGINSERVICES
    action:
      type: DECRYPT  # Options: BLOCK, DECRYPT, DO_NOT_DECRYPT
      override_default_certificate: false
      show_eun: false
      show_eunatp: false
      decrypt_sub_actions:
        block_ssl_traffic_with_no_sni_enabled: true
        block_undecrypt: true
        http2_enabled: true
        min_client_tls_version: CLIENT_TLS_1_2
        min_server_tls_version: SERVER_TLS_1_2
        ocsp_check: true
        server_certificates: BLOCK  # Options: ALLOW, BLOCK, PASS_THRU
      do_not_decrypt_sub_actions:
        block_ssl_traffic_with_no_sni_enabled: true
        bypass_other_policies: false
        min_tls_version: SERVER_TLS_1_2
        ocsp_check: true
        server_certificates: BLOCK  # Options: ALLOW, BLOCK
    state: present
  - name: 'SSL Inspection Rule - minimal'
    order: 15
    description: 'Minimal SSL Inspection Rule'
    enabled: true
    groups:
      - '{{ group_borgermeister }}'
    departments:
      - '{{ department_borgermeisterit }}'
    locations: []
    location_groups:
      - '{{ location_group_borgermeisterlocations }}'
    url_categories:
      - PROFESSIONAL_SERVICES
    cloud_applications:
      - MSLOGINSERVICES
    action:
      type: DO_NOT_DECRYPT  # Options: BLOCK, DECRYPT, DO_NOT_DECRYPT
      # override_default_certificate: false
      # show_eun: false
      # show_eunatp: false
      # decrypt_sub_actions:
      #   block_ssl_traffic_with_no_sni_enabled: true
      #   block_undecrypt: true
      #   http2_enabled: true
      #   min_client_tls_version: CLIENT_TLS_1_2
      #   min_server_tls_version: SERVER_TLS_1_2
      #   ocsp_check: true
      #   server_certificates: BLOCK  # Options: ALLOW, BLOCK, PASS_THRU
      # do_not_decrypt_sub_actions:
      #   block_ssl_traffic_with_no_sni_enabled: true
      #   bypass_other_policies: false
      #   min_tls_version: SERVER_TLS_1_2
      #   ocsp_check: true
      #   server_certificates: BLOCK  # Options: ALLOW, BLOCK
    state: present
