---

- name: Gather Information Details for all URL Categories
  zscaler.ziacloud.zia_cloud_browser_isolation_profile_info:
    provider: '{{ zscaler_zia }}'
  register: zia_cloud_browser_isolation_profile_info

- name: Delete file with all Browser Isolation Profiles
  ansible.builtin.file:
    path: '{{ role_path }}/files/browser_isolation_profiles.txt'
    state: absent

- name: Register all Browser Isolation Profiles to a file
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/files/browser_isolation_profiles.txt'
    create: true
    mode: '0644'
    state: present
    line: |
      Name: {{ item.name }}
      ID: {{ item.id }}
      URL: {{ item.url }}
  loop: "{{ zia_cloud_browser_isolation_profile_info.profiles }}"
